"""update models

Revision ID: 4e35950359eb
Revises: 6bf8d7a771af
Create Date: 2026-05-05 19:05:16.977787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e35950359eb'
down_revision = '6bf8d7a771af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('received_by', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('received_by')
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###
