"""push subscriptions

Revision ID: 61111896a937
Revises: 4e35950359eb
Create Date: 2026-05-09 11:14:14.239603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61111896a937'
down_revision = '4e35950359eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscription', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_subscription')
    # ### end Alembic commands ###
