"""add login security fields

Revision ID: 6bf8d7a771af
Revises: b75b6f907626
Create Date: 2026-05-05 18:36:13.018539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf8d7a771af'
down_revision = 'b75b6f907626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_allowed_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('next_allowed_login')
        batch_op.drop_column('failed_attempts')

    # ### end Alembic commands ###
