"""add package tracking table

Revision ID: cc9a17f69c2f
Revises: b0f2c27b4532
Create Date: 2026-08-29 13:11:19.184599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9a17f69c2f'
down_revision = 'b0f2c27b4532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('container_number', sa.String(length=50), nullable=True),
    sa.Column('current_status', sa.String(length=100), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_tracking_container_number'), ['container_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_tracking_package_id'), ['package_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_tracking_package_id'))
        batch_op.drop_index(batch_op.f('ix_package_tracking_container_number'))

    op.drop_table('package_tracking')
    # ### end Alembic commands ###
